### ISSUE TITLE
Creación obligatoria de Cliente y Caso [2]

### ISSUE THREAD

**Issue by AlexandraChen** [Carodlg/velo-cases#3]
# Job to be done
- [x] Para facturarle a un cliente, debe crearse previamente el caso, y para crear un caso debe haberse creado previamente el cliente.
- [x] Cases debe asegurar que este proceso ocurra siempre, sin excepciones.

**Comment by adrianagrimaldo** [comment]
Ya está creado que es requisito que es obligatorio poner el caso antes de crear la factura.
