### ISSUE TITLE
Ingresos Netos de Impuestos en reporte de Facturación [4]

### ISSUE THREAD

**Issue by AlexandraChen** [Carodlg/velo-cases#6]
# Job to be done
- [x] Agregar al reporte de Facturas una columna con los “Ingresos netos de impuestos”, que resulte de la resta entre los montos de la columna “Importe” y la columna “Impuesto total”.

**Comment by adrianagrimaldo** [comment]
Se le aclaró a Alexander que Necesitamos que en el reporte de pagos, nos aparezcan las siguientes columnas: Columna de "impuesto 7%" y columna con monto que resulta de la resta entre la columna de "importe" y la columna de impuesto que es el 7%.

**Comment by adrianagrimaldo** [comment]
job done
